# Generated by Django 5.2.7 on 2025-10-27 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unit_test', '0002_alter_blog_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='slug',
            field=models.SlugField(blank=True, max_length=300, null=True, unique=True),
        ),
    ]
